apiVersion: apps/v1
kind: Deployment
metadata:
  name: lambda-auth
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: lambda-auth
  template:
    metadata:
      labels:
        app: lambda-auth
    spec:
      containers:
        - name: lambda-auth
          image: gfrancodev/lambda-auth
          ports:
            - containerPort: 80  
          env:
            - name: SQLALCHEMY_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: lambda-auth-env
                  key: SQLALCHEMY_DATABASE_URI
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: lambda-auth-env
                  key: SECRET_KEY